### ISSUE TITLE
Term |MAX | Pre-prod | Quote Page | The premium is getting change on pop up when self employee is selected

### ISSUE THREAD

**Issue by sonavanediksha** [sadafaldar1911/Fyntune-TermEndowment-1.O#30]
**Describe the bug**
The premium is getting change on pop up when self employee is selected
"age 18
post graduate 
10 lakh"

**To Reproduce**
Sa1cr > cover upto 60> regular pay>select buy now>  select self employee> again buy now > see the premium 

**Expected behavior**
A pop up should work correctly, premium should not be change for salaried and self employee

**Journey URL**
https://preprodterm.elephant.in/quotes?enquiryId=202409131006062468

**Screenshots**
![image](https://github.com/user-attachments/assets/b0d8fb97-1fbe-4e3c-abda-460aa0e22363)
![image](https://github.com/user-attachments/assets/3c2347cd-a353-4773-99f5-a9b871444026)

**Trace id**
202409131006062468

**Telescope / Logs Link**
Add the telescope or Logs for where the error is reflected.

**Comment by Shiva87792** [comment]
@sonavanediksha 1911 This issue is from the frontend

**Comment by sonavanediksha** [comment]
Working correctly now. Retest Done
