### ISSUE TITLE
Term | MAX | Pre-prod | Eligibilty page | On  quote page at a time only one error should be display 

### ISSUE THREAD

**Issue by sonavanediksha** [sadafaldar1911/Fyntune-TermEndowment-1.O#31]
**Describe the bug**
On quote page at time only one error should be display.

**To Reproduce**
age 25, graduate, 1cr regular pay 
cover up to 60 year,select max life > buy now > select self employee > skip rideres > change occupation to below 10,> select occupation student > enter pincode 383460.

**Expected behavior**
Only one error should be display 

**Journey URL**
https://preprodterm.elephant.in/eligibilitypage?enquiryId=202409131046433066

**Screenshots**
![image](https://github.com/user-attachments/assets/0f81aee0-4c41-483f-96e6-69aa31eae8d0)

**Trace id**
202409131046433066

**Telescope / Logs Link**
Add the telescope or Logs for where the error is reflected.

**Comment by Shiva87792** [comment]
@sonavanediksha This issue is from the frontend.

**Comment by sonavanediksha** [comment]
Retest Done , Working propoerly
