### ISSUE TITLE
Term | MAX | Pre-prod | Eligibility page | When post graduate and agriculturest is selcted it will show error 

### ISSUE THREAD

**Issue by sonavanediksha** [sadafaldar1911/Fyntune-TermEndowment-1.O#32]
**Describe the bug**
For occupation agriculture, it should display the error 
age 18, post graduate , 1cr, 60 cover up to , regular pay

**To Reproduce**
select max life > self employee on pop up > on eligibility change the occupation to agriculture 

**Expected behavior**
when occupation is change to the agriculture error should be display 

**Journey URL**
https://preprodterm.elephant.in/eligibilitypage?enquiryId=202409131208077862

**Screenshots**
![image](https://github.com/user-attachments/assets/372eeef1-e423-4485-b61d-bb8049db25b9)

**Trace id**
202409131208077862

**Comment by Shiva87792** [comment]
@sonavanediksha 1911 This issue is from the frontend

**Comment by sonavanediksha** [comment]
Retest Done, Working fine
