### ISSUE TITLE
Term | ICICI | UAT | Eligibility page | when negative pin-code is enter must show the error , when occupation is selected as a housewife

### ISSUE THREAD

**Issue by sonavanediksha** [sadafaldar1911/Fyntune-TermEndowment-1.O#46]
**Describe the bug**
When an occupation is selected as a housewife, and negative pincode is enter must show the error for negative pincode

**Expected behavior**
For negative pincode when occupation housewife is selected must show the error 

**Journey URL**
https://termuat.elephant.in/eligibilitypage?enquiryId=202409261022102533

**Screenshots**
![image](https://github.com/user-attachments/assets/b09b43df-9728-496b-83f9-838088fdc79a)

**Trace id**
202409261022102533

**Comment by YogeshFyntune** [comment]
curl 'https://apitermuat.elephant.in/api/common/check_ipru_eligibility' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-GB,en;q=0.9,en-US;q=0.8' \
  -H 'Authorization: Bearer mJVCltBIbSOxpCG1Iyo4VCtOQHHOJ0rUERMastZz6yYAteog5yQpM0A49a9BsPFtYYdfMhiepuxbUeFY' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:3000' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'token: tneIq7PjCK9+j0cF6TkJNNMX/D1sbLKph3Z03Jnq+tRcSGDYhueIlPv7nYRbkuD3AoFIe2UG29hGDVTBWo0/xieSzEMotITiBRZAYGsArzDbOuKqkClRAn+LKon0NywOzw47SjX03frmiaEPZ65d1hI9RKKE4N3m2ujVyLO/XtU0vanFSRw0+9JKV0abh4ekeT+oQmwKQq/+nS8KwucqZeWxVg+X80ZBtZeEfYUSE3lcocp2/Mweb0daGC3/GmQtRVfJSlmgDtEcJN5r2hlVtkVcW5FzoavfwaZMwsHYaLBMotaDtGNQPXCKBkR1KF9gGkmdfzmS48+yfsF6yERJanIVOubIpOXsVpKicE4WYyDhOYcNkKSAeR/jOJGsdEgpO0K2cgw0n27kkkWN+Ay4dcmR94Phn1qRJJNnX6X67hO9vSAljJyAbqbEFXK8T3WmxS99tj41iv/2EAT01JRhhMjXGPM6IoVQkZZ3sYusr4RNNMkxUyDfg4O0XwPC+dPWmHSWUuRMGRfAV2Xw78p3FHhSuZgfUgPvvGFVSHCJr2ekBrAjm7/prgGJ/GxkW3Y9a2Fb50aR7GI1h4y0GDm5JfVDnBjc+y3hmCd//npSwYE=' \
  --data-raw '{"education_text":"Graduate","vaccinationStatus":"Please Select","occupation":"housewife","education":"graduate","occupation_text":"Housewife","is_nri":false,"annualIncome":1200000,"pincode":"110095","traceId":"202409261156009464"}'
  
  
  pincode_type is not getting in response for housewife
  
  @Shiva87792 @sonavanediksha

**Comment by sonavanediksha** [comment]
Retest done , Issue is fix
![image](https://github.com/user-attachments/assets/959c48eb-fdcb-4ac5-9ddb-102881e6beaf)
