### ISSUE TITLE
Term | Pre-Prod | Go-Digit | Quote page | When click on the compare plan the Go-Digit plan name comes to next line refer screen short

### ISSUE THREAD

**Issue by kamblemayuri29** [sadafaldar1911/Fyntune-TermEndowment-1.O#89]
**Describe the bug**
 When click on the compare plan the Go-Digit plan name comes to next line refer screen short

**To Reproduce**

**Expected behavior**
Plan name should be proper 

**Journey URL**
https://preprodterm.elephant.in/quotes?enquiryId=202412040316266101&&src=home

**Screenshots**
With out compare
![image](https://github.com/user-attachments/assets/cc698946-f288-4ffa-9f97-75a1482e736a)
with compare
![image](https://github.com/user-attachments/assets/12c8e745-6f7c-439a-b9ee-0599a7e7890f)

**Trace id**
202412040316266101

**Comment by sonavanediksha** [comment]
![image](https://github.com/user-attachments/assets/59efc8ca-14d5-4163-9114-bc4f289d5717)
Issue is fix , Retest Done
