### ISSUE TITLE
Term | Pre-Prod |UAT  | Go-Digit | Quote page | Salaried pop  continue content should be capital letter .

### ISSUE THREAD

**Issue by kamblemayuri29** [sadafaldar1911/Fyntune-TermEndowment-1.O#90]
**Describe the bug**
 Salaried pop  continue content should be capital letter .

**To Reproduce**

**Expected behavior**

**Continue content** should be capital letter

**Journey URL**
https://preprodterm.elephant.in/quotes?enquiryId=202412040339451472

**Screenshots**
![image](https://github.com/user-attachments/assets/83899a77-f500-4591-952c-a4154898f596)

**Comment by sonavanediksha** [comment]
![image](https://github.com/user-attachments/assets/02414b1e-e5b8-406b-af50-f777cb668d15)
Issue is fix, Retest Done
