### ISSUE TITLE
Term | UAT | Pre-Prod | Go-Digit | Proposal page | Remove the parentheses of the plan name of the go-digit refer screen short 

### ISSUE THREAD

**Issue by kamblemayuri29** [sadafaldar1911/Fyntune-TermEndowment-1.O#91]
**Describe the bug**
Remove the parentheses of the plan name of the go-digit  and Total premium payable first latter  should be capital refer screen short 

**Expected behavior**

**Journey URL**
https://preprodterm.elephant.in/eligibilitypage?enquiryId=202412040402578115

**Screenshots**
![image](https://github.com/user-attachments/assets/b60450e2-db97-4ff2-b822-1521924329f6)

**Comment by sonavanediksha** [comment]
![image](https://github.com/user-attachments/assets/07c7bacc-54e0-4380-9860-21dea036213a)
Retest Done, Issue is Fix
